data: './data/'
batch_size: 256
log: './log/'
epoch: 30
epoch_ckp: 0
optim: 'adam'
learning_rate: 0.0001
max_grad_norm: 8
learning_rate_decay: 0.5
schedule: True
start_decay_at: 0
dropout: 0.1
num_head: 8
step: 2
max_length: 50
lm_path: './log/lm_newlr'
lm_restore: '0.4568111300468445_checkpoint.pt'
lm_path_n: './log/lm_n_1lr'
lm_restore_n: '0.3264918029308319_checkpoint.pt'
pic_path: './log/pic_newlr'
pic_restore: '67440_updates_checkpoint.pt'
mt_path: './log/lmp_50e_mt_cl'
mt_restore: '1-112400_updates_checkpoint.pt'